function guide(key, label, emoji, aliases, phrases, requiredAny, response, faqTerms = []) {
  return {
    key, label, action: 'SHOW_GUIDE', emoji, priority: 'normal', optionAliases: aliases,
    phrases, requiredAny, response, faqTerms, buttonLabel: 'CẦN STAFF HỖ TRỢ',
  };
}

function ticket(key, label, emoji, priority, aliases, phrases, requiredAny, response, buttonLabel) {
  return {
    key, label, action: 'CREATE_TICKET', emoji, priority, optionAliases: aliases,
    phrases, requiredAny, response, buttonLabel,
  };
}

export const INTENTS = [
  ticket(
    'ITEM_LOSS_DUE_TO_LAG', 'Mất vật phẩm do lag', '📦', 'high',
    ['mất vật phẩm', 'mất đồ', 'hoàn đồ', 'survival', 'hỗ trợ chung'],
    [
      ['chet mat do', 1], ['lag mat do', 1], ['server lag mat do', 1],
      ['rollback mat do', 0.98], ['bay het do', 0.94], ['mat inventory', 0.94],
      ['do bien mat', 0.88], ['chet luc lag', 0.94], ['mat vat pham do loi server', 1],
      ['bi clear inventory', 0.9], ['disconnect mat do', 0.9],
    ],
    [['mat', 'bay', 'bien mat', 'clear'], ['do', 'inventory', 'vat pham']],
    'Trường hợp của bạn cần staff kiểm tra log máy chủ, thời gian chết và vật phẩm bị mất.',
    'TẠO TICKET MẤT ĐỒ',
  ),
  ticket(
    'TOPUP_NOT_RECEIVED', 'Nạp tiền chưa nhận', '💳', 'high',
    ['nạp thẻ', 'nạp tiền', 'thanh toán', 'donate', 'hỗ trợ chung'],
    [
      ['nap roi chua nhan', 1], ['nap tien khong vao', 1], ['nap the khong nhan', 1],
      ['chuyen khoan chua nhan', 0.98], ['mat tien nap', 0.94], ['loi thanh toan', 0.9],
      ['khong nhan xu', 0.96], ['khong nhan rank', 0.96], ['bi tru tien nhung khong nhan', 1],
    ],
    [['nap', 'thanh toan', 'chuyen khoan'], ['chua nhan', 'khong nhan', 'loi', 'mat', 'tru tien']],
    'Giao dịch cần được đối chiếu mã nạp, thời gian và tài khoản Minecraft trước khi xử lý.',
    'BÁO LỖI NẠP TIỀN',
  ),
  ticket(
    'PURCHASE_DELIVERY_ERROR', 'Mua sản phẩm nhưng chưa nhận', '🛒', 'high',
    ['mua rank', 'mua vật phẩm', 'shop', 'store', 'hỗ trợ chung'],
    [
      ['mua rank chua nhan', 1], ['mua do chua nhan', 1], ['store khong giao do', 0.98],
      ['mua key khong nhan', 0.94], ['mua vat pham bi loi', 0.92], ['don hang bi loi', 0.9],
    ],
    [['mua', 'store', 'don hang'], ['chua nhan', 'khong nhan', 'loi']],
    'Hãy giữ lại mã giao dịch và tạo ticket để staff kiểm tra việc giao sản phẩm.',
    'BÁO LỖI ĐƠN HÀNG',
  ),
  ticket(
    'BUG_REPORT', 'Báo lỗi server', '🐛', 'normal',
    ['báo lỗi', 'bug', 'lỗi server', 'hỗ trợ chung'],
    [
      ['bao loi', 0.92], ['server bi loi', 0.94], ['gap bug', 1],
      ['loi plugin', 0.94], ['khong dung duoc lenh', 0.84], ['bi crash', 0.9],
      ['dupe bug', 0.92], ['loi game', 0.82], ['plugin khong hoat dong', 0.9],
    ],
    [['loi', 'bug', 'crash'], ['server', 'plugin', 'lenh', 'game', 'tinh nang']],
    'Lỗi này nên được ghi nhận trong ticket để staff có đủ mô tả, ảnh hoặc video và thời gian xảy ra.',
    'TẠO TICKET BÁO LỖI',
  ),
  ticket(
    'PLAYER_REPORT', 'Báo cáo người chơi', '🚨', 'high',
    ['báo cáo người chơi', 'tố cáo', 'report', 'hỗ trợ chung'],
    [
      ['report nguoi choi', 1], ['to cao nguoi choi', 1], ['nguoi choi hack', 0.98],
      ['bi lua dao', 0.94], ['bi scam', 0.94], ['pha hoai', 0.84],
      ['to cao staff', 0.9], ['player vi pham', 0.9], ['quay roi', 0.84],
    ],
    [['report', 'to cao', 'hack', 'lua dao', 'scam', 'vi pham'], ['nguoi choi', 'player', 'staff', 'toi']],
    'Bạn nên tạo ticket riêng và gửi tên người chơi, thời gian cùng bằng chứng để tránh công khai thông tin nhạy cảm.',
    'TẠO TICKET BÁO CÁO',
  ),
  ticket(
    'PUNISHMENT_APPEAL', 'Kháng án hình phạt', '⚖️', 'normal',
    ['kháng án', 'ban appeal', 'mute appeal', 'hỗ trợ chung'],
    [
      ['khang an', 1], ['xin unban', 1], ['bi ban oan', 0.98], ['bi mute oan', 0.98],
      ['go ban', 0.9], ['go mute', 0.9], ['xin giam an', 0.86], ['appeal ban', 0.94],
    ],
    [['ban', 'mute', 'khang an', 'hinh phat'], ['oan', 'xin', 'go', 'appeal', 'giam']],
    'Kháng án cần được gửi riêng để staff kiểm tra lý do phạt và bằng chứng liên quan.',
    'TẠO TICKET KHÁNG ÁN',
  ),
  ticket(
    'ACCOUNT_SECURITY', 'Tài khoản bị chiếm hoặc có rủi ro', '🔐', 'high',
    ['tài khoản', 'bảo mật', 'hỗ trợ chung'],
    [
      ['mat tai khoan', 1], ['tai khoan bi hack', 1], ['bi doi mat khau', 0.98],
      ['bi chiem acc', 1], ['lo thong tin tai khoan', 0.9], ['nguoi khac vao acc', 0.96],
    ],
    [['tai khoan', 'acc'], ['mat', 'hack', 'chiem', 'doi mat khau', 'nguoi khac']],
    'Không gửi mật khẩu hoặc OTP. Hãy tạo ticket riêng để staff xác minh bằng dữ liệu an toàn.',
    'TẠO TICKET TÀI KHOẢN',
  ),
  ticket(
    'STAFF_APPLICATION', 'Ứng tuyển Staff', '🛡️', 'normal',
    ['ứng tuyển staff', 'tuyển staff', 'staff', 'helper', 'hỗ trợ chung'],
    [
      ['xin lam staff', 1], ['ung tuyen staff', 1], ['tuyen staff', 0.98],
      ['lam helper', 0.94], ['lam admin', 0.9], ['lam mod', 0.9], ['nop don staff', 0.96],
    ],
    [['staff', 'helper', 'admin', 'mod'], ['xin', 'ung tuyen', 'tuyen', 'lam', 'nop don']],
    'Bạn có thể gửi đơn ứng tuyển để staff quản lý xem xét kinh nghiệm và thời gian hoạt động.',
    'ỨNG TUYỂN STAFF',
  ),

  guide(
    'STAFF_REQUIREMENTS', 'Yêu cầu tuyển Staff', '🧑‍💼',
    ['ứng tuyển staff', 'staff', 'hỗ trợ chung'],
    [['dieu kien lam staff', 1], ['yeu cau staff', 1], ['bao nhieu tuoi lam staff', 0.94], ['staff can gi', 0.92], ['tuyen vi tri nao', 0.9]],
    [['staff'], ['dieu kien', 'yeu cau', 'tuoi', 'can gi', 'vi tri']],
    'Mình sẽ tìm điều kiện và vị trí tuyển dụng đang được quản trị viên công bố.',
    ['staff', 'ứng tuyển', 'điều kiện'],
  ),
  guide(
    'TOPUP_GUIDE', 'Hướng dẫn nạp tiền', '💳',
    ['nạp thẻ', 'nạp tiền', 'thanh toán', 'hỗ trợ chung'],
    [['nap the o dau', 1], ['cach nap the', 1], ['cach nap tien', 1], ['huong dan nap', 0.98], ['mua xu o dau', 0.92], ['nap xu', 0.86]],
    [['nap', 'mua xu'], ['cach', 'o dau', 'huong dan']],
    'Mình sẽ tìm hướng dẫn nạp tiền chính thức của server cho bạn.',
    ['nạp thẻ', 'nạp tiền', 'thanh toán', 'mua xu'],
  ),
  guide(
    'RANK_INFO', 'Thông tin Rank', '👑',
    ['rank', 'store', 'nạp tiền', 'hỗ trợ chung'],
    [['rank co gi', 1], ['quyen loi rank', 1], ['gia rank', 0.96], ['cac rank server', 0.94], ['rank nao tot', 0.9], ['mua rank', 0.86]],
    [['rank'], ['quyen loi', 'gia', 'co gi', 'cac', 'mua']],
    'Mình sẽ tra quyền lợi và thông tin rank đã được cập nhật trong Knowledge Base.',
    ['rank', 'quyền lợi', 'giá rank'],
  ),
  guide(
    'DONATION_INFO', 'Ủng hộ server', '💖',
    ['donate', 'ủng hộ', 'nạp tiền', 'hỗ trợ chung'],
    [['ung ho server', 1], ['cach donate', 0.98], ['donate server', 0.98], ['quyen loi donate', 0.94], ['muon ung ho', 0.94]],
    [['ung ho', 'donate'], ['cach', 'muon', 'quyen loi', 'server']],
    'Cảm ơn bạn đã muốn ủng hộ server. Mình sẽ lấy thông tin chính thức để tránh nhầm phương thức hoặc quyền lợi.',
    ['ủng hộ', 'donate', 'quyền lợi'],
  ),
  guide(
    'EVENT_INFO', 'Thông tin sự kiện', '🎉',
    ['sự kiện', 'event', 'hỗ trợ chung'],
    [['hom nay co event gi', 1], ['su kien khi nao', 0.98], ['lich su kien', 1], ['event con khong', 0.9], ['su kien hien tai', 0.94], ['event moi', 0.86]],
    [['event', 'su kien'], ['khi nao', 'may gio', 'lich', 'hom nay', 'con khong', 'hien tai', 'moi']],
    'Mình sẽ tra thông tin sự kiện hiện có trong kho hướng dẫn của server.',
    ['sự kiện', 'event', 'lịch'],
  ),
  guide(
    'BOSS_SCHEDULE', 'Lịch Boss', '🐉',
    ['boss', 'sự kiện', 'hỗ trợ chung'],
    [['boss may gio', 1], ['boss khi nao', 1], ['lich boss', 1], ['boss spawn luc nao', 0.98], ['boss o dau', 0.9]],
    [['boss'], ['may gio', 'khi nao', 'lich', 'spawn', 'o dau']],
    'Mình sẽ tra lịch và địa điểm boss đã được staff cập nhật.',
    ['boss', 'lịch boss', 'spawn boss'],
  ),
  guide(
    'KOTH_SCHEDULE', 'Lịch KOTH', '🏰',
    ['koth', 'sự kiện', 'hỗ trợ chung'],
    [['koth may gio', 1], ['koth khi nao', 1], ['lich koth', 1], ['koth o dau', 0.92], ['cach choi koth', 0.9]],
    [['koth'], ['may gio', 'khi nao', 'lich', 'o dau', 'cach choi']],
    'Mình sẽ tra lịch và hướng dẫn KOTH hiện tại.',
    ['koth', 'lịch koth'],
  ),
  guide(
    'SERVER_STATUS', 'Tình trạng server', '📡',
    ['server', 'hỗ trợ chung'],
    [['server bi sap', 0.94], ['server offline', 1], ['server sao khong vao duoc', 1], ['server bao tri', 0.92], ['server co online khong', 0.98]],
    [['server'], ['offline', 'khong vao', 'bao tri', 'online', 'sap']],
    'Mình sẽ kiểm tra hướng dẫn hoặc thông báo trạng thái server đang được lưu trong hệ thống.',
    ['trạng thái server', 'bảo trì', 'offline', 'không vào được'],
  ),
  guide(
    'SERVER_LAG', 'Server lag hoặc TPS thấp', '📉',
    ['server', 'báo lỗi', 'hỗ trợ chung'],
    [['server lag', 1], ['lag qua', 0.94], ['tps thap', 1], ['giat lag', 0.96], ['server dung hinh', 0.98], ['delay cao', 0.94]],
    [['lag', 'tps', 'delay', 'dung hinh'], ['server', 'game', 'qua', 'thap', 'cao']],
    'Mình sẽ đưa các bước kiểm tra nhanh; nếu nhiều người cùng gặp, bạn có thể báo staff.',
    ['server lag', 'TPS', 'MSPT', 'độ trễ'],
  ),
  guide(
    'LOGIN_CONNECTION_HELP', 'Không vào được server', '🔌',
    ['server', 'tài khoản', 'hỗ trợ chung'],
    [['khong vao duoc server', 1], ['ket noi that bai', 0.98], ['bi kick khi vao', 0.94], ['mat ket noi', 0.9], ['connection refused', 0.96], ['unknown host', 0.94]],
    [['server', 'ket noi', 'vao'], ['khong', 'that bai', 'kick', 'mat', 'refused', 'unknown']],
    'Mình sẽ kiểm tra phiên bản, địa chỉ server và các lỗi kết nối thường gặp.',
    ['không vào được', 'kết nối', 'địa chỉ server'],
  ),
  guide(
    'VERSION_HELP', 'Phiên bản Minecraft hỗ trợ', '🧩',
    ['server', 'hướng dẫn', 'hỗ trợ chung'],
    [['server phien ban bao nhieu', 1], ['choi version nao', 1], ['minecraft bao nhieu', 0.94], ['ho tro phien ban nao', 1], ['java hay bedrock', 0.9]],
    [['version', 'phien ban', 'minecraft', 'java', 'bedrock'], ['bao nhieu', 'nao', 'ho tro', 'choi']],
    'Mình sẽ tra phiên bản và loại client được server hỗ trợ.',
    ['phiên bản', 'Minecraft', 'Java', 'Bedrock'],
  ),
  guide(
    'RESOURCE_PACK_HELP', 'Lỗi Resource Pack', '🎨',
    ['resource pack', 'pack', 'texture', 'hỗ trợ chung'],
    [['loi resource pack', 1], ['khong tai duoc pack', 1], ['pack bi loi', 0.98], ['texture bi loi', 0.94], ['khong hien model', 0.92], ['pack bi vang den', 0.9]],
    [['pack', 'resource', 'texture', 'model'], ['loi', 'khong tai', 'khong hien', 'vang den']],
    'Mình sẽ đưa các bước kiểm tra Resource Pack; nếu vẫn lỗi, bạn có thể tạo ticket kèm latest.log.',
    ['resource pack', 'texture', 'model', 'latest.log'],
  ),
  guide(
    'BEGINNER_GUIDE', 'Hướng dẫn người chơi mới', '🌱',
    ['tân thủ', 'hướng dẫn', 'hỗ trợ chung'],
    [['nguoi moi lam gi', 1], ['huong dan tan thu', 1], ['moi vao server', 0.96], ['bat dau nhu the nao', 0.94], ['choi server sao', 0.9]],
    [['nguoi moi', 'tan thu', 'moi vao', 'bat dau'], ['lam gi', 'huong dan', 'nhu the nao', 'choi']],
    'Mình sẽ hướng dẫn các bước đầu tiên và những lệnh quan trọng dành cho người chơi mới.',
    ['tân thủ', 'người mới', 'bắt đầu'],
  ),
  guide(
    'COMMAND_HELP', 'Tra cứu lệnh server', '⌨️',
    ['hướng dẫn', 'lệnh', 'hỗ trợ chung'],
    [['lenh gi', 0.9], ['danh sach lenh', 1], ['lenh server', 1], ['command nao', 0.94], ['cach dung lenh', 0.96]],
    [['lenh', 'command'], ['gi', 'danh sach', 'server', 'nao', 'cach dung']],
    'Mình sẽ tìm đúng nhóm lệnh bạn đang cần.',
    ['lệnh', 'command', 'hướng dẫn'],
  ),
  guide(
    'CLAIM_GUIDE', 'Claim và bảo vệ đất', '🧱',
    ['claim', 'bảo vệ đất', 'hỗ trợ chung'],
    [['cach claim dat', 1], ['bao ve dat', 0.98], ['mo rong claim', 0.94], ['xoa claim', 0.94], ['them ban vao claim', 0.92], ['claim bi loi', 0.86]],
    [['claim', 'bao ve dat'], ['cach', 'mo rong', 'xoa', 'them', 'loi']],
    'Mình sẽ tra hướng dẫn claim, chia quyền và dịch chuyển về khu đất.',
    ['claim', 'bảo vệ đất', 'trust'],
  ),
  guide(
    'RTP_WARP_GUIDE', 'RTP và Warp', '🧭',
    ['rtp', 'warp', 'hướng dẫn', 'hỗ trợ chung'],
    [['cach rtp', 1], ['rtp la gi', 0.94], ['danh sach warp', 1], ['warp o dau', 0.96], ['di den khu nao', 0.86], ['teleport ngau nhien', 0.94]],
    [['rtp', 'warp', 'teleport'], ['cach', 'la gi', 'danh sach', 'o dau', 'ngau nhien']],
    'Mình sẽ tra lệnh RTP, warp và chỉ dẫn di chuyển phù hợp.',
    ['rtp', 'warp', 'dịch chuyển'],
  ),
  guide(
    'STORE_GUIDE', 'Cửa hàng và /store', '🛍️',
    ['store', 'shop', 'hỗ trợ chung'],
    [['store o dau', 1], ['cach mo store', 1], ['lenh store', 0.98], ['mua do o dau', 0.9], ['cua hang server', 0.94]],
    [['store', 'shop', 'cua hang', 'mua do'], ['o dau', 'cach', 'lenh', 'server']],
    'Mình sẽ tra hướng dẫn mở cửa hàng và các lưu ý khi mua sản phẩm.',
    ['store', 'shop', 'cửa hàng'],
  ),
  guide(
    'GIFT_CODE_GUIDE', 'Gift Code', '🎁',
    ['code', 'giftcode', 'hỗ trợ chung'],
    [['nhap code o dau', 1], ['cach nhap code', 1], ['code server', 0.94], ['giftcode', 0.94], ['code khong dung duoc', 0.9], ['ma qua tang', 0.94]],
    [['code', 'giftcode', 'ma qua tang'], ['o dau', 'cach', 'server', 'khong dung', 'nhap']],
    'Mình sẽ hướng dẫn cách nhập Gift Code và xử lý các lỗi thường gặp.',
    ['code', 'giftcode', 'mã quà tặng'],
  ),
  guide(
    'KIT_GUIDE', 'Kit và thời gian nhận lại', '🎒',
    ['kit', 'hướng dẫn', 'hỗ trợ chung'],
    [['cach nhan kit', 1], ['kit o dau', 1], ['bao lau nhan lai kit', 0.98], ['kit bi cooldown', 0.94], ['lenh kit', 0.94]],
    [['kit'], ['cach', 'o dau', 'bao lau', 'cooldown', 'lenh']],
    'Mình sẽ tra danh sách kit, lệnh nhận và thời gian chờ hiện tại.',
    ['kit', 'cooldown kit'],
  ),
  guide(
    'FISHING_GUIDE', 'Hệ thống câu cá', '🎣',
    ['câu cá', 'fishing', 'hỗ trợ chung'],
    [['cach cau ca', 1], ['can cau nao tot', 0.94], ['ca hiem o dau', 0.94], ['fishing', 0.86], ['event cau ca', 0.9], ['skill can cau', 0.9]],
    [['cau ca', 'fishing', 'can cau', 'ca hiem'], ['cach', 'nao', 'o dau', 'event', 'skill']],
    'Mình sẽ tra hướng dẫn câu cá, cần câu và khu vực liên quan.',
    ['câu cá', 'cần câu', 'EvenMoreFish'],
  ),
  guide(
    'CHICKEN_FARM_GUIDE', 'Trang trại gà', '🐔',
    ['chicken', 'gà', 'nông trại', 'hỗ trợ chung'],
    [['cach nuoi ga', 1], ['mua trung ga o dau', 0.98], ['dat o ga', 1], ['ga bi chet', 0.94], ['chicken2', 0.9], ['trang trai ga', 0.94]],
    [['ga', 'chicken', 'trung', 'o ga'], ['cach', 'o dau', 'dat', 'chet', 'trang trai']],
    'Mình sẽ hướng dẫn mua trứng, đặt ổ gà và chăm sóc trang trại.',
    ['gà', 'trứng', 'ổ gà', 'chicken2'],
  ),
  guide(
    'DUNGEON_GUIDE', 'Dungeon', '⚔️',
    ['dungeon', 'hướng dẫn', 'hỗ trợ chung'],
    [['cach vao dungeon', 1], ['dungeon o dau', 1], ['can gi vao dungeon', 0.94], ['dungeon key', 0.94], ['boss dungeon', 0.9], ['ai dungeon', 0.86]],
    [['dungeon'], ['cach', 'o dau', 'can gi', 'key', 'boss', 'ai']],
    'Mình sẽ tra điều kiện, chìa khóa và hướng dẫn dungeon phù hợp.',
    ['dungeon', 'dungeon key', 'boss dungeon'],
  ),
  guide(
    'TRADE_GUIDE', 'Trade và nâng cấp vật phẩm', '🔨',
    ['trade', 'nâng cấp', 'hỗ trợ chung'],
    [['cach trade do', 1], ['nang cap do o dau', 1], ['trade npc', 0.94], ['cong thuc trade', 0.94], ['blueprint la gi', 0.9]],
    [['trade', 'nang cap', 'blueprint'], ['cach', 'o dau', 'npc', 'cong thuc', 'la gi']],
    'Mình sẽ tra NPC, nguyên liệu và quy trình nâng cấp vật phẩm.',
    ['trade', 'nâng cấp', 'blueprint'],
  ),
  guide(
    'AUCTION_GUIDE', 'Chợ đấu giá', '🏷️',
    ['auction', 'chợ', 'hỗ trợ chung'],
    [['cach ban do', 0.96], ['cho dau gia', 1], ['auction house', 0.94], ['dang ban vat pham', 0.94], ['mua do nguoi choi', 0.9]],
    [['auction', 'cho dau gia', 'dang ban', 'ban do'], ['cach', 'mua', 'nguoi choi', 'vat pham']],
    'Mình sẽ tra lệnh và quy định sử dụng chợ đấu giá.',
    ['auction', 'chợ đấu giá', 'AxAuctions'],
  ),
  guide(
    'QUEST_GUIDE', 'Nhiệm vụ và Quest', '📜',
    ['quest', 'nhiệm vụ', 'hỗ trợ chung'],
    [['cach lam quest', 1], ['nhiem vu o dau', 1], ['quest khong tinh', 0.94], ['nhan nhiem vu', 0.94], ['phan thuong quest', 0.9]],
    [['quest', 'nhiem vu'], ['cach', 'o dau', 'khong tinh', 'nhan', 'phan thuong']],
    'Mình sẽ tra nơi nhận nhiệm vụ, yêu cầu và cách xử lý khi tiến độ không được tính.',
    ['quest', 'nhiệm vụ'],
  ),
  guide(
    'MOB_COIN_GUIDE', 'MobCoin', '🪙',
    ['mobcoin', 'soul', 'hỗ trợ chung'],
    [['mobcoin la gi', 1], ['kiem mobcoin', 1], ['soul la gi', 0.92], ['mua bang mobcoin', 0.94], ['mobcoin o dau', 0.9]],
    [['mobcoin', 'soul'], ['la gi', 'kiem', 'mua', 'o dau']],
    'Mình sẽ tra cách kiếm và sử dụng MobCoin trong server.',
    ['mobcoin', 'soul'],
  ),
  guide(
    'HOME_TPA_GUIDE', 'Home, TPA và dịch chuyển người chơi', '🏠',
    ['home', 'tpa', 'dịch chuyển', 'hỗ trợ chung'],
    [['cach set home', 1], ['lenh home', 0.96], ['tpa nhu the nao', 1], ['teleport toi ban', 0.96], ['xoa home', 0.94], ['khong tpa duoc', 0.9]],
    [['home', 'tpa', 'teleport'], ['cach', 'lenh', 'xoa', 'khong duoc', 'toi ban']],
    'Mình sẽ tra hướng dẫn đặt home, gửi yêu cầu dịch chuyển và các giới hạn hiện tại.',
    ['home', 'tpa', 'dịch chuyển người chơi'],
  ),
  guide(
    'ECONOMY_SHOP_GUIDE', 'Kinh tế và cửa hàng trong game', '💰',
    ['shop', 'kinh tế', 'tiền game', 'hỗ trợ chung'],
    [['kiem tien nhu the nao', 1], ['ban do o dau', 0.96], ['shop mua ban', 1], ['gia vat pham', 0.9], ['kiem xu', 0.9], ['tien game la gi', 0.9]],
    [['tien', 'shop', 'mua ban', 'gia', 'xu'], ['kiem', 'o dau', 'nhu the nao', 'vat pham']],
    'Mình sẽ tìm cách kiếm tiền, nơi mua bán và loại tiền phù hợp với hoạt động của bạn.',
    ['kinh tế', 'shop', 'tiền game', 'PlayerPoints'],
  ),
  guide(
    'CRATE_KEY_GUIDE', 'Rương và chìa khóa', '🗝️',
    ['crate', 'key', 'rương', 'hỗ trợ chung'],
    [['mo ruong o dau', 1], ['key dung o dau', 1], ['cach dung chia khoa', 0.98], ['crate khong mo duoc', 0.94], ['mat key', 0.9], ['ti le ruong', 0.88]],
    [['crate', 'key', 'ruong', 'chia khoa'], ['o dau', 'cach dung', 'khong mo', 'mat', 'ti le']],
    'Mình sẽ tra vị trí rương, loại chìa khóa và cách xử lý khi key không hoạt động.',
    ['crate', 'key', 'rương', 'chìa khóa'],
  ),
  guide(
    'AFK_GUIDE', 'Khu AFK và phần thưởng', '💤',
    ['afk', 'phần thưởng', 'hỗ trợ chung'],
    [['afk o dau', 1], ['khu afk', 1], ['afk duoc gi', 0.96], ['khong nhan thuong afk', 0.94], ['afk bao lau', 0.9]],
    [['afk'], ['o dau', 'khu', 'duoc gi', 'khong nhan', 'bao lau']],
    'Mình sẽ tra cách tới khu AFK, điều kiện nhận thưởng và các giới hạn liên quan.',
    ['afk', 'khu AFK', 'phần thưởng AFK'],
  ),
  guide(
    'PVP_GUIDE', 'PvP và khu chiến đấu', '⚔️',
    ['pvp', 'đấu trường', 'hỗ trợ chung'],
    [['pvp o dau', 1], ['cach vao pvp', 1], ['mat do khi pvp', 0.94], ['luat pvp', 0.96], ['tat pvp', 0.86]],
    [['pvp', 'dau truong'], ['o dau', 'cach vao', 'mat do', 'luat', 'tat']],
    'Mình sẽ tra vị trí khu PvP, luật chiến đấu và quy định mất vật phẩm hiện tại.',
    ['pvp', 'đấu trường', 'luật PvP'],
  ),
  guide(
    'CLAN_COMMUNITY_GUIDE', 'Clan và cộng đồng', '🏘️',
    ['clan', 'làng', 'cộng đồng', 'hỗ trợ chung'],
    [['cach tao clan', 1], ['vao clan nhu the nao', 0.98], ['moi thanh vien clan', 0.94], ['lang cong dong', 0.96], ['roi clan', 0.9]],
    [['clan', 'lang', 'cong dong'], ['cach tao', 'vao', 'moi', 'roi', 'thanh vien']],
    'Mình sẽ tra cách tạo hoặc tham gia nhóm cộng đồng và các quyền thành viên.',
    ['clan', 'làng cộng đồng', 'thành viên'],
  ),
  guide(
    'MARRIAGE_GUIDE', 'Kết hôn và wedding', '💍',
    ['wedding', 'kết hôn', 'hỗ trợ chung'],
    [['cach ket hon', 1], ['wedding o dau', 0.96], ['ly hon nhu the nao', 0.94], ['moi cuoi', 0.94], ['teleport vo chong', 0.9]],
    [['ket hon', 'wedding', 'ly hon', 'cuoi'], ['cach', 'o dau', 'nhu the nao', 'teleport']],
    'Mình sẽ tra quy trình kết hôn, khu wedding và các lệnh liên quan.',
    ['kết hôn', 'wedding', 'ly hôn'],
  ),
  guide(
    'STORAGE_GUIDE', 'Kho đồ, vault và backpack', '🧰',
    ['vault', 'backpack', 'kho đồ', 'hỗ trợ chung'],
    [['mo backpack', 1], ['vault o dau', 1], ['kho do bi mat', 0.96], ['balo khong mo duoc', 0.94], ['them o kho', 0.88]],
    [['vault', 'backpack', 'balo', 'kho do'], ['mo', 'o dau', 'bi mat', 'khong mo', 'them o']],
    'Mình sẽ tra cách sử dụng kho đồ; nếu dữ liệu biến mất, hãy ngừng thao tác và tạo ticket ngay.',
    ['vault', 'backpack', 'kho đồ'],
  ),
  guide(
    'SMP_COMMUNITY_GUIDE', 'SMP cộng đồng', '🌿',
    ['smp', 'cộng đồng', 'hỗ trợ chung'],
    [['cach choi smp', 1], ['smp co gi', 0.96], ['tham gia cong dong smp', 0.94], ['smp thuong khac gi', 0.92]],
    [['smp'], ['cach choi', 'co gi', 'cong dong', 'khac gi']],
    'Mình sẽ dùng hướng dẫn của cụm SMP, không trộn với ChunkySMP hoặc Survival.',
    ['SMP', 'cộng đồng SMP', 'hướng dẫn SMP'],
  ),
  guide(
    'SKYBLOCK_ISLAND_GUIDE', 'Đảo Skyblock', '☁️',
    ['skyblock', 'đảo', 'hỗ trợ chung'],
    [['cach tao dao skyblock', 1], ['lenh island', 0.98], ['moi ban vao dao', 0.96], ['xoa dao skyblock', 0.94], ['ve dao cua toi', 0.92]],
    [['dao', 'island', 'skyblock'], ['tao', 'lenh', 'moi', 'xoa', 've']],
    'Mình sẽ tra đúng lệnh tạo đảo, quản lý thành viên và dịch chuyển của Skyblock.',
    ['skyblock', 'island', 'đảo', 'thành viên đảo'],
  ),
  guide(
    'SKYBLOCK_UPGRADE_GUIDE', 'Nâng cấp đảo Skyblock', '⬆️',
    ['skyblock', 'nâng cấp đảo', 'hỗ trợ chung'],
    [['nang cap dao skyblock', 1], ['tang cap island', 0.98], ['generator skyblock', 0.96], ['minion skyblock', 0.94], ['mo rong dao', 0.92]],
    [['skyblock', 'island', 'dao'], ['nang cap', 'generator', 'minion', 'mo rong']],
    'Mình sẽ tìm cấp đảo, generator, minion và điều kiện nâng cấp đúng của Skyblock.',
    ['nâng cấp đảo', 'generator', 'minion', 'level island'],
  ),
  guide(
    'BOXPVP_MINE_GUIDE', 'Khu mine BoxPvP', '📦',
    ['boxpvp', 'mine', 'hỗ trợ chung'],
    [['mine boxpvp o dau', 1], ['reset mine boxpvp', 0.98], ['dao khoang boxpvp', 0.96], ['khu box bi loi', 0.92]],
    [['boxpvp', 'box', 'mine'], ['o dau', 'reset', 'dao khoang', 'loi']],
    'Mình sẽ tra khu mine, thời gian reset và tiến trình khai thác riêng của BoxPvP.',
    ['BoxPvP', 'mine', 'reset mine', 'khu box'],
  ),
  guide(
    'BOXPVP_GEAR_GUIDE', 'Trang bị BoxPvP', '🗡️',
    ['boxpvp', 'trang bị', 'hỗ trợ chung'],
    [['nang cap do boxpvp', 1], ['set do boxpvp nao tot', 0.98], ['kiem trang bi boxpvp', 0.96], ['mat do khi pvp box', 0.94]],
    [['boxpvp', 'box'], ['nang cap do', 'trang bi', 'set do', 'mat do']],
    'Mình sẽ tra đúng tuyến trang bị, nâng cấp và quy định PvP của BoxPvP.',
    ['BoxPvP', 'trang bị', 'nâng cấp đồ', 'set PvP'],
  ),
  guide(
    'TU_TIEN_CULTIVATION_GUIDE', 'Tu luyện và cảnh giới', '🪷',
    ['tu tiên', 'cảnh giới', 'hỗ trợ chung'],
    [['cach tu luyen tu tien', 1], ['canh gioi tu tien', 0.98], ['kiem linh khi', 0.96], ['tang tu vi', 0.94]],
    [['tu tien', 'tu luyen', 'canh gioi'], ['cach', 'linh khi', 'tang', 'tu vi']],
    'Mình sẽ tra tiến trình tu luyện, linh khí và cảnh giới riêng của cụm Tu Tiên.',
    ['tu luyện', 'cảnh giới', 'linh khí', 'tu vi'],
  ),
  guide(
    'TU_TIEN_BREAKTHROUGH_GUIDE', 'Đột phá Tu Tiên', '✨',
    ['tu tiên', 'đột phá', 'hỗ trợ chung'],
    [['cach dot pha tu tien', 1], ['dot pha that bai', 0.98], ['can gi de dot pha', 0.96], ['bi canh tu tien', 0.92]],
    [['tu tien', 'dot pha', 'bi canh'], ['cach', 'that bai', 'can gi']],
    'Mình sẽ tra điều kiện đột phá, vật phẩm cần thiết và bí cảnh đúng của Tu Tiên.',
    ['đột phá', 'bí cảnh', 'vật phẩm Tu Tiên'],
  ),
  guide(
    'FFA_KIT_GUIDE', 'Kit và đấu trường FFA', '⚔️',
    ['ffa', 'kit', 'hỗ trợ chung'],
    [['chon kit ffa', 1], ['vao arena ffa', 0.98], ['kit ffa nao tot', 0.96], ['respawn ffa o dau', 0.92]],
    [['ffa', 'arena'], ['kit', 'vao', 'nao tot', 'respawn']],
    'Mình sẽ tra kit, arena và cách respawn riêng của FFA.',
    ['FFA', 'kit FFA', 'arena', 'respawn'],
  ),
  guide(
    'FFA_RANKING_GUIDE', 'Xếp hạng FFA', '🏆',
    ['ffa', 'xếp hạng', 'hỗ trợ chung'],
    [['xem top ffa', 1], ['bang xep hang ffa', 0.98], ['tinh diem ffa', 0.96], ['kill streak ffa', 0.94]],
    [['ffa'], ['top', 'xep hang', 'diem', 'kill streak']],
    'Mình sẽ tra bảng xếp hạng, cách tính điểm và chuỗi hạ gục của FFA.',
    ['top FFA', 'xếp hạng', 'điểm FFA', 'kill streak'],
  ),
  guide(
    'CHUNKYSMP_CHUNK_GUIDE', 'Chunk và bảo vệ ChunkySMP', '🧊',
    ['chunkysmp', 'chunk', 'hỗ trợ chung'],
    [['cach claim chunk chunkysmp', 1], ['mua chunk chunky smp', 0.98], ['them ban vao chunk', 0.96], ['chunkysmp khac smp', 0.94]],
    [['chunkysmp', 'chunky smp', 'chunk'], ['claim', 'mua', 'them ban', 'khac']],
    'Mình sẽ dùng cơ chế chunk của ChunkySMP, không áp dụng hướng dẫn claim của SMP thường.',
    ['ChunkySMP', 'chunk', 'claim chunk', 'thành viên chunk'],
  ),

  guide(
    'RULES_INFO', 'Quy định server', '📚',
    ['quy định', 'luật', 'hỗ trợ chung'],
    [['quy dinh server', 1], ['luat server', 1], ['co duoc lam vay khong', 0.88], ['hanh vi bi cam', 0.96], ['noi quy', 0.94]],
    [['quy dinh', 'luat', 'noi quy', 'bi cam'], ['server', 'lam vay', 'hanh vi']],
    'Mình sẽ tìm đúng mục quy định liên quan; các trường hợp chưa rõ sẽ được chuyển staff.',
    ['quy định', 'luật server', 'nội quy'],
  ),
  guide(
    'DISCORD_LINK_HELP', 'Liên kết Discord', '🔗',
    ['discord', 'liên kết', 'hỗ trợ chung'],
    [['lien ket discord', 1], ['link tai khoan discord', 1], ['verify discord', 0.94], ['khong nhan role discord', 0.92], ['discord link loi', 0.94]],
    [['discord'], ['lien ket', 'link', 'verify', 'role', 'loi']],
    'Mình sẽ tra cách liên kết tài khoản và nhận role Discord.',
    ['Discord', 'liên kết tài khoản', 'verify'],
  ),
];

export const UNKNOWN_INTENT = {
  key: 'UNKNOWN_SUPPORT',
  label: 'Yêu cầu hỗ trợ khác',
  action: 'ASK_CLARIFICATION',
  emoji: '❓',
  priority: 'normal',
  optionAliases: ['hỗ trợ chung'],
  response: 'Mình chưa xác định chắc vấn đề. Bạn có thể chọn nhóm gần nhất hoặc mô tả thêm một câu.',
  buttonLabel: 'TẠO TICKET HỖ TRỢ',
};

export const INTENT_MAP = new Map(INTENTS.map((intent) => [intent.key, intent]));
